### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hyperdriveguy** [nephitejnf/muse2pokecrystal#15]
Lower priority, but we probably want to throw a license on this bad boy at some point (because we can).

My recommendation would be GPLv3 for code (maybe even AGPL...even though muse2pokecrystal isn't designed to run on a server at this point) and CC0 for the MusicXML template.

**Comment by nephitejnf** [comment]
True, I'll double check the stuff in GPL3 to refresh.

**Comment by nephitejnf** [comment]
We gots a loicense for that
